### ISSUE TITLE
BUG:第二天发送签到会显示你今天已经签到过了

### ISSUE THREAD

**Issue by Yuk1Nok4zE** [azmiao/pcr_almanac#1]
服务器环境为CentOS7.6
插件是直接clone的当前版本，所有代码未改动
安装使用后，第二天再发送签到会提示“你今天已经签到过啦！”
尝试修改get_all_info.py逻辑未果（我太菜了），作者抽空看看这个bug，我不知道是不是只有我存在这个bug；

**Comment by azmiao** [comment]
我这边测试没问题，正常来说每天24点整会有定时任务删除当天所有签到过的信息，麻烦你打开插件文件夹/data文件夹下看看昨天的签到信息是否还存在，因为我这边00：00的时候定时任务正常清理了文件，所以我猜测是不是你那定时任务没有运行之类的或者运行报错之类的

**Comment by azmiao** [comment]
你试试把`__init__.py`的第19行和20行换成这个：
'''
@sv.on_fullmatch('测试删除')
async def clean_dir(bot, ev):
'''
然后随便找个群去发一句测试删除，看看有没有报错，然后也看看/data/里面的文件有没有清空

**Comment by Yuk1Nok4zE** [comment]
> 你试试把`__init__.py`的第19行和20行换成这个： ''' @sv.on_fullmatch('测试删除') async def clean_dir(bot, ev): ''' 然后随便找个群去发一句测试删除，看看有没有报错，然后也看看/data/里面的文件有没有清空

谢谢作者，原来是因为Linux中读取路径跟windows那个斜杠正好是反着来的，它的数据全都写到插件根目录里去了，现在已经解决了

**Comment by azmiao** [comment]
好耶
